name: release

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: 1.17
#      - name: reviewdog up
#        uses: reviewdog/action-setup@v1
#      - name: reviewdog
#        run: reviewdog -conf=.reviewdog.yml -reporter=local
      - name: build
        env:
          RELEASE_VERSION: ${{ github.ref_name }}
        run: ./scripts/binary.sh darwin && ./scripts/binary.sh darwin-m1 && ./scripts/binary.sh windows && ./scripts/binary.sh linux && sha256sum ./dist/*
      - name: update
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/docker-debug-darwin-amd64
            dist/docker-debug-darwin-arm64
            dist/docker-debug-linux-amd64
            dist/docker-debug-windows-amd64.exe
